### ISSUE TITLE
Docker is not downloading dependencies in build

### ISSUE THREAD

**Issue by sdurban** [phpcoach/users#6]
@mmoreram Since we add vendor folder to docker build context composer is just passing by and ignoring it.

Maybe we can ignore vendor folder in .dockerignore?

**WARNING: It will make docker build slower.**

**Comment by mmoreram** [comment]
Composer installs it in case vendor is empty (what could happen somehow)
Otherwise will ignore the folder, what makes sense.
This package is not designed to be production ready, so I think that this part makes sense.
